version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "10:00"
      timezone: America/Chicago
    open-pull-requests-limit: 5
    groups:
      all-npm-dependencies:
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: npm
    directory: /examples/with-typescript-nextane
    schedule:
      interval: daily
      time: "10:10"
      timezone: America/Chicago
    open-pull-requests-limit: 2
    groups:
      all-example-dependencies:
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: npm
    directory: /benchmarks/pages-compare
    schedule:
      interval: daily
      time: "10:20"
      timezone: America/Chicago
    open-pull-requests-limit: 2
    groups:
      all-benchmark-dependencies:
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "10:30"
      timezone: America/Chicago
    open-pull-requests-limit: 5
    groups:
      all-github-actions:
        patterns:
          - "*"
